#_______________________________________________________________
# Tut mogla bit vasha reklama! 
#_______________________________________________________________


name: my_gh_basics_actions

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  
  my_test_job:
    
    runs-on: ubuntu-latest

    steps:
 
#    - uses: actions/checkout@v2
 
    - name: Run a one-line script
      run: echo Hello, world!

  
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
