#_______________________________________________________________
# Tut mogla bit vasha reklama! 
#_______________________________________________________________


name: my_gh_basics_actions

on:
  push:
    branches: [ master ]

jobs:
  my_test_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
        run: echo Hello, world! 
