#_______________________________________________________________
# Zdes mogla bit vasha reklama!! 
#     d-_-b
#     (.)(.)
#_______________________________________________________________

name: my_ansible_deplay
  
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
           
    - name: Install python pip, ansible-lint
      run: |
         python -m pip install --upgrade pip
         pip install ansible ansible-lint
         
    - name: Lint playbook
      run: |
         ansible-playbook site.yml --syntax-check
         ansible-lint site.yml
    
    
    
    
    
    
    
    
    
   
   
   
   
   
 #    env:
 #      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
 #      AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
 #    run: |
 #      echo "$ANSIBLE_VAULT_PASSWORD" > .ansible-vault-password
 #      mkdir .ssh
 #      echo "$AWS_SSH_KEY" > .ssh/id_ubuntu_18_04
 #      chmod 600 .ssh/id_ubuntu_18_04
 #  - name: run exporters playbook
 #    env:
 #      AWS_API_KEY: ${{ secrets.AWS_API_KEY }}
 #    run: |
 #      ansible-playbook -i inventory play.yml
    
    
    
